// ==========================================================================
// PORTAL DATA - Comprehensive Dataset for OnCampus / Kaarya Skilling Platform
// Covers: Trainees, Courses, Programs, Providers, Employers, Alerts, Audits, Users
// ==========================================================================

export const money = (value) => `₹${Number(value || 0).toLocaleString("en-IN")}`;

export function exportCsv(filename, rows) {
  if (!rows || !rows.length) return false;
  const columns = Object.keys(rows[0]);
  const escapeCell = (value) => `"${String(value ?? "").replaceAll('"', '""')}"`;
  const content = [columns, ...rows.map((row) => columns.map((column) => row[column]))]
    .map((row) => row.map(escapeCell).join(","))
    .join("\r\n");
  const blob = new Blob([content], { type: "text/csv;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
  return true;
}

export function exportJson(filename, data) {
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  link.click();
  URL.revokeObjectURL(url);
  return true;
}

export const initialTrainees = [
  {
    id: "SK-24018",
    name: "Aarav Mehta",
    initials: "AM",
    city: "Pune, Maharashtra",
    district: "Pune",
    state: "Maharashtra",
    course: "Solar PV Installation",
    courseId: "CRS-SOL-01",
    provider: "Udaan Skills Centre",
    trained: "12 Feb 2025",
    employer: "SunGrid Energy",
    role: "Solar Technician",
    department: "Field Engineering",
    manager: "Vikram Sen",
    joiningDate: "12 Jan 2026",
    contractType: "Full-time Permanent",
    wage: 18500,
    startingWage: 15500,
    status: "Employed",
    followup: "Due today",
    consent: true,
    gender: "Male",
    age: 23,
    phone: "+91 98••• ••421",
    email: "aarav.mehta@example.in",
    verified: true,
    retention: "8 months",
    retentionMonths: 8,
    change: 18,
    attendancePct: 94,
    assessmentScore: 86,
    certId: "NSQF-4-SOL-2025-091",
    batchId: "BATCH-2024-SOL-A",
    qualification: "Diploma in Electrical",
    nsqfLevel: "Level 4",
    skills: ["Solar PV Installation", "Inverter Commissioning", "Electrical Safety", "Grid Sync"],
    appraisalHistory: [
      { date: "12 Jan 2026", role: "Junior Trainee", wage: 15500, note: "Initial Placement" },
      { date: "15 Jun 2026", role: "Solar Technician", wage: 18500, note: "Appraisal for performance" },
    ],
  },
  {
    id: "SK-24027",
    name: "Priya Nair",
    initials: "PN",
    city: "Kochi, Kerala",
    district: "Ernakulam",
    state: "Kerala",
    course: "Healthcare Assistant",
    courseId: "CRS-HLT-02",
    provider: "Saksham Foundation",
    trained: "04 Mar 2025",
    employer: "Aster Medcity",
    role: "Patient Care Assistant",
    department: "Inpatient Care",
    manager: "Dr. Rachel Thomas",
    joiningDate: "15 Mar 2026",
    contractType: "Full-time Permanent",
    wage: 21000,
    startingWage: 18500,
    status: "Employed",
    followup: "In 3 days",
    consent: true,
    gender: "Female",
    age: 25,
    phone: "+91 97••• ••856",
    email: "priya.nair@example.in",
    verified: true,
    retention: "6 months",
    retentionMonths: 6,
    change: 13,
    attendancePct: 98,
    assessmentScore: 92,
    certId: "NSQF-4-HLT-2025-112",
    batchId: "BATCH-2024-HLT-B",
    qualification: "B.Sc General Science",
    nsqfLevel: "Level 4",
    skills: ["Vitals Monitoring", "Patient Hygiene", "First Aid", "Medication Admin"],
    appraisalHistory: [
      { date: "15 Mar 2026", role: "Junior Assistant", wage: 18500, note: "Joining offer" },
      { date: "15 Aug 2026", role: "Patient Care Assistant", wage: 21000, note: "Probation successfully completed" },
    ],
  },
  {
    id: "SK-24033",
    name: "Imran Khan",
    initials: "IK",
    city: "Jaipur, Rajasthan",
    district: "Jaipur",
    state: "Rajasthan",
    course: "Retail Sales Associate",
    courseId: "CRS-RET-03",
    provider: "Kaushal Pragati",
    trained: "19 Jan 2025",
    employer: "",
    role: "",
    department: "",
    manager: "",
    joiningDate: "",
    contractType: "",
    wage: 0,
    startingWage: 0,
    status: "Seeking work",
    followup: "Overdue",
    consent: true,
    gender: "Male",
    age: 21,
    phone: "+91 99••• ••037",
    email: "imran.k@example.in",
    verified: false,
    retention: "-",
    retentionMonths: 0,
    change: 0,
    attendancePct: 88,
    assessmentScore: 78,
    certId: "NSQF-3-RET-2025-045",
    batchId: "BATCH-2024-RET-A",
    qualification: "Higher Secondary (12th)",
    nsqfLevel: "Level 3",
    skills: ["POS Software", "Customer Handling", "Inventory Audit", "Visual Merchandising"],
    appraisalHistory: [],
  },
  {
    id: "SK-24041",
    name: "Kavya Reddy",
    initials: "KR",
    city: "Hyderabad, Telangana",
    district: "Hyderabad",
    state: "Telangana",
    course: "Data Entry & Office Tools",
    courseId: "CRS-DAT-04",
    provider: "Nirmaan Trust",
    trained: "27 Feb 2025",
    employer: "Self-employed",
    role: "Freelance Data Operator",
    department: "Freelance / Micro-enterprise",
    manager: "Self",
    joiningDate: "10 Mar 2026",
    contractType: "Independent Contractor",
    wage: 24000,
    startingWage: 18000,
    status: "Self-employed",
    followup: "In 12 days",
    consent: true,
    gender: "Female",
    age: 24,
    phone: "+91 96••• ••512",
    email: "kavya.reddy@example.in",
    verified: true,
    retention: "7 months",
    retentionMonths: 7,
    change: 33,
    attendancePct: 96,
    assessmentScore: 94,
    certId: "NSQF-4-DAT-2025-201",
    batchId: "BATCH-2024-DAT-A",
    qualification: "B.Com",
    nsqfLevel: "Level 4",
    skills: ["MS Excel / Google Sheets", "Data Cleansing", "Tally ERP", "Bilingual Typing"],
    appraisalHistory: [
      { date: "10 Mar 2026", role: "Freelance Data Operator", wage: 18000, note: "Initial monthly client retainer" },
      { date: "01 Jul 2026", role: "Senior Data Contractor", wage: 24000, note: "Expanded client contracts" },
    ],
  },
  {
    id: "SK-24056",
    name: "Sanjay Das",
    initials: "SD",
    city: "Kolkata, West Bengal",
    district: "Kolkata",
    state: "West Bengal",
    course: "Electric Vehicle Service",
    courseId: "CRS-EVS-05",
    provider: "Udaan Skills Centre",
    trained: "10 Apr 2025",
    employer: "Volt Motors",
    role: "Service Apprentice",
    department: "Battery & Drivetrain Workshop",
    manager: "Arindam Bose",
    joiningDate: "02 May 2026",
    contractType: "Apprenticeship (NAPS)",
    wage: 16000,
    startingWage: 14500,
    status: "Apprentice",
    followup: "Due today",
    consent: true,
    gender: "Male",
    age: 22,
    phone: "+91 90••• ••194",
    email: "sanjay.das@example.in",
    verified: false,
    retention: "4 months",
    retentionMonths: 4,
    change: 10,
    attendancePct: 91,
    assessmentScore: 84,
    certId: "NSQF-4-EVS-2025-088",
    batchId: "BATCH-2025-EVS-A",
    qualification: "ITI Motor Mechanic",
    nsqfLevel: "Level 4",
    skills: ["EV Battery Diagnostics", "Regen Braking", "High Voltage Safety", "ECU Scan"],
    appraisalHistory: [
      { date: "02 May 2026", role: "Apprentice Trainee", wage: 14500, note: "Government Stipend + Employer Top-up" },
      { date: "01 Aug 2026", role: "Service Apprentice", wage: 16000, note: "Skill level test increment" },
    ],
  },
  {
    id: "SK-24063",
    name: "Meena Kumari",
    initials: "MK",
    city: "Patna, Bihar",
    district: "Patna",
    state: "Bihar",
    course: "Healthcare Assistant",
    courseId: "CRS-HLT-02",
    provider: "Saksham Foundation",
    trained: "15 Mar 2025",
    employer: "CareWell Clinic",
    role: "Care Assistant",
    department: "Geriatric & Palliative",
    manager: "Dr. S. K. Roy",
    joiningDate: "01 Apr 2026",
    contractType: "Full-time Permanent",
    wage: 17500,
    startingWage: 15000,
    status: "Employed",
    followup: "Completed",
    consent: true,
    gender: "Female",
    age: 27,
    phone: "+91 91••• ••668",
    email: "meena.k@example.in",
    verified: true,
    retention: "5 months",
    retentionMonths: 5,
    change: 16,
    attendancePct: 95,
    assessmentScore: 89,
    certId: "NSQF-4-HLT-2025-139",
    batchId: "BATCH-2024-HLT-C",
    qualification: "12th Pass",
    nsqfLevel: "Level 4",
    skills: ["Elderly Care", "Vital Checks", "CPR & First Aid", "Sterilization"],
    appraisalHistory: [
      { date: "01 Apr 2026", role: "Care Assistant", wage: 15000, note: "Probation" },
      { date: "01 Jul 2026", role: "Senior Care Assistant", wage: 17500, note: "Confirmed" },
    ],
  },
  {
    id: "SK-24072",
    name: "Rohan Varma",
    initials: "RV",
    city: "Pune, Maharashtra",
    district: "Pune",
    state: "Maharashtra",
    course: "Solar PV Installation",
    courseId: "CRS-SOL-01",
    provider: "Udaan Skills Centre",
    trained: "18 May 2025",
    employer: "SunGrid Energy",
    role: "Solar Installer",
    department: "Rooftop Projects",
    manager: "Vikram Sen",
    joiningDate: "01 Jun 2026",
    contractType: "Full-time",
    wage: 19000,
    startingWage: 16000,
    status: "Employed",
    followup: "In 18 days",
    consent: true,
    gender: "Male",
    age: 24,
    phone: "+91 95••• ••309",
    email: "rohan.varma@example.in",
    verified: true,
    retention: "4 months",
    retentionMonths: 4,
    change: 18,
    attendancePct: 92,
    assessmentScore: 88,
    certId: "NSQF-4-SOL-2025-144",
    batchId: "BATCH-2025-SOL-B",
    qualification: "ITI Electrician",
    nsqfLevel: "Level 4",
    skills: ["Rooftop PV Mounting", "Wiring & Earthing", "Safety Harness Handling"],
    appraisalHistory: [
      { date: "01 Jun 2026", role: "Solar Installer", wage: 16000, note: "Joining" },
      { date: "01 Sep 2026", role: "Solar Lead Installer", wage: 19000, note: "Project completion bonus incorporated" },
    ],
  },
  {
    id: "SK-24088",
    name: "Ananya Deshmukh",
    initials: "AD",
    city: "Nagpur, Maharashtra",
    district: "Nagpur",
    state: "Maharashtra",
    course: "Data Entry & Office Tools",
    courseId: "CRS-DAT-04",
    provider: "Nirmaan Trust",
    trained: "14 Jun 2025",
    employer: "SunGrid Energy",
    role: "Operations Support Associate",
    department: "Supply Chain & ERP",
    manager: "Sneha Kulkarni",
    joiningDate: "10 Jul 2026",
    contractType: "Full-time Permanent",
    wage: 20500,
    startingWage: 18000,
    status: "Employed",
    followup: "In 7 days",
    consent: true,
    gender: "Female",
    age: 23,
    phone: "+91 93••• ••714",
    email: "ananya.d@example.in",
    verified: false,
    retention: "3 months",
    retentionMonths: 3,
    change: 14,
    attendancePct: 97,
    assessmentScore: 95,
    certId: "NSQF-4-DAT-2025-302",
    batchId: "BATCH-2025-DAT-B",
    qualification: "B.A. Economics",
    nsqfLevel: "Level 4",
    skills: ["Advanced Excel", "ERP Data Entry", "Inventory Requisition", "Vendor Emailing"],
    appraisalHistory: [
      { date: "10 Jul 2026", role: "Operations Support", wage: 18000, note: "Probationary offer" },
      { date: "15 Sep 2026", role: "Operations Associate", wage: 20500, note: "Accelerated confirmation" },
    ],
  },
  {
    id: "SK-24095",
    name: "Vikram Chauhan",
    initials: "VC",
    city: "Jaipur, Rajasthan",
    district: "Jaipur",
    state: "Rajasthan",
    course: "Electric Vehicle Service",
    courseId: "CRS-EVS-05",
    provider: "Kaushal Pragati",
    trained: "20 May 2025",
    employer: "Volt Motors",
    role: "EV Service Technician",
    department: "Diagnostics Center",
    manager: "Manoj Rathore",
    joiningDate: "15 Jun 2026",
    contractType: "Full-time",
    wage: 22000,
    startingWage: 19000,
    status: "Employed",
    followup: "In 22 days",
    consent: true,
    gender: "Male",
    age: 26,
    phone: "+91 92••• ••889",
    email: "vikram.c@example.in",
    verified: false,
    retention: "3 months",
    retentionMonths: 3,
    change: 15,
    attendancePct: 90,
    assessmentScore: 87,
    certId: "NSQF-4-EVS-2025-104",
    batchId: "BATCH-2025-EVS-B",
    qualification: "Diploma in Automobile",
    nsqfLevel: "Level 4",
    skills: ["BMS Troubleshooting", "Motor Overhaul", "CAN Bus Protocol", "Thermal Management"],
    appraisalHistory: [
      { date: "15 Jun 2026", role: "EV Technician", wage: 19000, note: "Starting offer" },
      { date: "01 Sep 2026", role: "EV Specialist", wage: 22000, note: "Master diagnostics certification passed" },
    ],
  },
  {
    id: "SK-24102",
    name: "Fatima Sheikh",
    initials: "FS",
    city: "Lucknow, Uttar Pradesh",
    district: "Lucknow",
    state: "Uttar Pradesh",
    course: "Healthcare Assistant",
    courseId: "CRS-HLT-02",
    provider: "Saksham Foundation",
    trained: "10 Jul 2025",
    employer: "",
    role: "",
    department: "",
    manager: "",
    joiningDate: "",
    contractType: "",
    wage: 0,
    startingWage: 0,
    status: "Seeking work",
    followup: "Due today",
    consent: true,
    gender: "Female",
    age: 22,
    phone: "+91 94••• ••551",
    email: "fatima.s@example.in",
    verified: false,
    retention: "-",
    retentionMonths: 0,
    change: 0,
    attendancePct: 93,
    assessmentScore: 82,
    certId: "NSQF-4-HLT-2025-219",
    batchId: "BATCH-2025-HLT-D",
    qualification: "12th Science",
    nsqfLevel: "Level 4",
    skills: ["Infection Control", "Specimen Handling", "Bedside Monitoring", "Biomedical Waste"],
    appraisalHistory: [],
  },
];

export const initialCourses = [
  {
    id: "CRS-SOL-01",
    title: "Solar PV Installation",
    code: "SGJ/Q0101",
    sector: "Green Jobs / Renewable Energy",
    provider: "Udaan Skills Centre",
    duration: "420 Hours (14 Weeks)",
    theoryHours: 120,
    practicalHours: 240,
    ojtHours: 60,
    nsqfLevel: "Level 4",
    enrolled: 1240,
    certified: 1165,
    placed: 893,
    placementRate: 72,
    retentionRate: 81,
    medianWage: 18500,
    status: "Active",
    demand: "High Demand (+24% YoY)",
    skillsCovered: ["Solar PV Modules", "Inverter Wiring", "Earthing & Lightning Arrestor", "Grid Connectivity", "Fault Diagnosis"],
    outcomes: "Prepares learners for NSQF certified roles as Solar Installation Technicians, Rooftop Supervisors, and Maintenance Engineers.",
    syllabus: [
      "Module 1: Foundations of Photovoltaic Systems & Site Survey",
      "Module 2: Structural Mounting & Module Interconnection",
      "Module 3: Inverters, Batteries, & Power Conditioning Units",
      "Module 4: Safety Norms, Personal Protective Equipment, & Electrical Codes",
      "Module 5: Testing, Commissioning, & Customer Handover Protocols",
    ],
  },
  {
    id: "CRS-HLT-02",
    title: "Healthcare Assistant",
    code: "HSS/Q5102",
    sector: "Healthcare & Allied Services",
    provider: "Saksham Foundation",
    duration: "480 Hours (16 Weeks)",
    theoryHours: 160,
    practicalHours: 220,
    ojtHours: 100,
    nsqfLevel: "Level 4",
    enrolled: 980,
    certified: 872,
    placed: 666,
    placementRate: 68,
    retentionRate: 76,
    medianWage: 21000,
    status: "Active",
    demand: "High Demand (+31% YoY)",
    skillsCovered: ["Vitals Measurement", "Patient Hygiene & Transfer", "Infection Control", "First Aid & CPR", "Electronic Health Records"],
    outcomes: "Accredited pathway for Patient Care Associates, Hospital Aides, and Home Healthcare Assistants across Tier-1 and Tier-2 hospitals.",
    syllabus: [
      "Module 1: Human Anatomy & Basic Physiology",
      "Module 2: Aseptic Techniques & Biomedical Waste Management",
      "Module 3: Patient Care Ergonomics & Ambulation",
      "Module 4: Emergency First Response & BLS Guidelines",
      "Module 5: Clinical Documentation & Soft Skills for Caregivers",
    ],
  },
  {
    id: "CRS-EVS-05",
    title: "Electric Vehicle Service",
    code: "ASC/Q1422",
    sector: "Automotive & Electric Mobility",
    provider: "Udaan Skills Centre",
    duration: "360 Hours (12 Weeks)",
    theoryHours: 100,
    practicalHours: 180,
    ojtHours: 80,
    nsqfLevel: "Level 4",
    enrolled: 640,
    certified: 557,
    placed: 474,
    placementRate: 74,
    retentionRate: 83,
    medianWage: 19500,
    status: "Active",
    demand: "Growing Demand (+42% YoY)",
    skillsCovered: ["High Voltage Safety", "Battery Management System", "Traction Motor Servicing", "Regenerative Braking", "OBD Diagnostics"],
    outcomes: "Equips trainees with specialized skills for 2W, 3W, and 4W electric mobility servicing, OEM dealership workshops, and fleet maintenance.",
    syllabus: [
      "Module 1: EV Architecture, Motors, and Energy Storage Systems",
      "Module 2: High-Voltage Safety Protocol & Lockout-Tagout",
      "Module 3: Battery Pack Diagnostics & Cell Balancing",
      "Module 4: Motor Controllers & Regenerative Power Transfer",
      "Module 5: Diagnostic Scanners & Wiring Harness Repair",
    ],
  },
  {
    id: "CRS-DAT-04",
    title: "Data Entry & Office Tools",
    code: "SSC/Q2212",
    sector: "IT-ITeS & Digital Services",
    provider: "Nirmaan Trust",
    duration: "300 Hours (10 Weeks)",
    theoryHours: 80,
    practicalHours: 200,
    ojtHours: 20,
    nsqfLevel: "Level 4",
    enrolled: 720,
    certified: 691,
    placed: 439,
    placementRate: 61,
    retentionRate: 69,
    medianWage: 17200,
    status: "Active",
    demand: "Moderate Demand (Review Needed)",
    skillsCovered: ["Spreadsheet Modeling", "Database Management", "Tally & Financial Ledger", "Speed Typing", "Customer Helpdesk"],
    outcomes: "Prepares candidates for Office Assistants, Junior Data Analysts, and BPO Back-office operations.",
    syllabus: [
      "Module 1: Keyboard Ergonomics & High-Speed Touch Typing",
      "Module 2: Advanced Formulas, VLOOKUP, & Pivot Tables",
      "Module 3: Google Workspace & Collaborative Cloud Suites",
      "Module 4: Business Correspondence & Customer Ticketing",
      "Module 5: Basic Data Validation & Cybersecurity Hygiene",
    ],
  },
  {
    id: "CRS-RET-03",
    title: "Retail Sales Associate",
    code: "RAS/Q0104",
    sector: "Retail & Consumer Goods",
    provider: "Kaushal Pragati",
    duration: "280 Hours (8 Weeks)",
    theoryHours: 90,
    practicalHours: 150,
    ojtHours: 40,
    nsqfLevel: "Level 3",
    enrolled: 860,
    certified: 783,
    placed: 490,
    placementRate: 57,
    retentionRate: 62,
    medianWage: 16000,
    status: "Under Review",
    demand: "Slowing Demand",
    skillsCovered: ["Store Merchandising", "POS Billing Software", "Customer Upselling", "Inventory Auditing", "Grievance Handling"],
    outcomes: "Provides floor readiness for modern hypermarkets, apparel chains, and electronic retail counters.",
    syllabus: [
      "Module 1: Customer Journey & Greeting Protocols",
      "Module 2: Point of Sale Terminal Hardware & Barcode Scanning",
      "Module 3: Inventory Stock Taking & Shelf Replenishment",
      "Module 4: Cross-Selling, Up-Selling, and Discount Calculation",
      "Module 5: Shrinkage Prevention & Return Merchandising",
    ],
  },
];

export const initialBatches = [
  { id: "BATCH-2024-SOL-A", course: "Solar PV Installation", trainer: "K. R. Pillai", students: 30, attendanceAvg: 93, completionRate: 96, status: "Graduated", center: "Pune Centre #1" },
  { id: "BATCH-2024-HLT-B", course: "Healthcare Assistant", trainer: "Sister Mary V.", students: 35, attendanceAvg: 95, completionRate: 94, status: "Graduated", center: "Kochi Health Hub" },
  { id: "BATCH-2025-EVS-A", course: "Electric Vehicle Service", trainer: "Arvind Joshi", students: 25, attendanceAvg: 89, completionRate: 91, status: "Graduated", center: "Kolkata Tech Lab" },
  { id: "BATCH-2025-DAT-B", course: "Data Entry & Office Tools", trainer: "Pooja Hegde", students: 32, attendanceAvg: 94, completionRate: 97, status: "Active", center: "Hyderabad Digital" },
  { id: "BATCH-2025-SOL-B", course: "Solar PV Installation", trainer: "Sunil Verma", students: 28, attendanceAvg: 91, completionRate: 93, status: "Active", center: "Pune Centre #2" },
];

export const initialTrainingPrograms = [
  { id: "PRG-PMKVY-4", name: "Pradhan Mantri Kaushal Vikas Yojana 4.0", code: "PMKVY-4.0", ministry: "MSDE", budget: "₹1,200 Cr", activeCenters: 420, enrolledTrainees: 45000, placementBenchmark: "70%", status: "Active" },
  { id: "PRG-DDU-GKY", name: "Deen Dayal Upadhyaya Grameen Kaushalya Yojana", code: "DDU-GKY", ministry: "MoRD", budget: "₹850 Cr", activeCenters: 310, enrolledTrainees: 32000, placementBenchmark: "70%", status: "Active" },
  { id: "PRG-NAPS", name: "National Apprenticeship Promotion Scheme", code: "NAPS-2", ministry: "MSDE", budget: "₹450 Cr", activeCenters: 180, enrolledTrainees: 18500, placementBenchmark: "80%", status: "Active" },
  { id: "PRG-SMART-SKILL", name: "State Mission for Advanced Readiness Training", code: "SMART-ST", ministry: "State Government", budget: "₹320 Cr", activeCenters: 95, enrolledTrainees: 12400, placementBenchmark: "65%", status: "Active" },
];

export const initialTrainingProviders = [
  { id: "PRV-UDAAN", name: "Udaan Skills Centre", centers: 8, districts: ["Pune", "Kolkata", "Nagpur"], coursesCount: 5, enrolled: 2480, placedRate: 72, retentionRate: 81, auditScore: "94/100", status: "Compliant" },
  { id: "PRV-SAKSHAM", name: "Saksham Foundation", centers: 6, districts: ["Kochi", "Patna", "Lucknow"], coursesCount: 4, enrolled: 1960, placedRate: 68, retentionRate: 76, auditScore: "89/100", status: "Compliant" },
  { id: "PRV-NIRMAAN", name: "Nirmaan Trust", centers: 5, districts: ["Hyderabad", "Bengaluru"], coursesCount: 3, enrolled: 1720, placedRate: 61, retentionRate: 69, auditScore: "84/100", status: "Warning Issued" },
  { id: "PRV-KAUSHAL", name: "Kaushal Pragati", centers: 4, districts: ["Jaipur", "Jodhpur"], coursesCount: 3, enrolled: 1140, placedRate: 57, retentionRate: 62, auditScore: "78/100", status: "Under Review" },
];

export const initialEmployers = [
  { id: "EMP-SUNGRID", name: "SunGrid Energy", sector: "Renewable Energy", location: "Pune & Pan-India", activeHires: 486, verifiedHires: 479, avgStartingWage: 18500, sixMonthRetention: "82%", contactPerson: "Rohan Desai (People Ops)", status: "Active Partner" },
  { id: "EMP-ASTER", name: "Aster Medcity", sector: "Healthcare", location: "Kochi, Kerala", activeHires: 312, verifiedHires: 308, avgStartingWage: 21000, sixMonthRetention: "79%", contactPerson: "Dr. Rachel Thomas", status: "Active Partner" },
  { id: "EMP-VOLT", name: "Volt Motors", sector: "Automotive / EV", location: "Kolkata & Pune", activeHires: 224, verifiedHires: 210, avgStartingWage: 19500, sixMonthRetention: "84%", contactPerson: "Arindam Bose", status: "Active Partner" },
  { id: "EMP-CAREWELL", name: "CareWell Clinic", sector: "Healthcare", location: "Patna & Lucknow", activeHires: 145, verifiedHires: 140, avgStartingWage: 17500, sixMonthRetention: "74%", contactPerson: "S. K. Roy", status: "Active Partner" },
  { id: "EMP-TATA-PWR", name: "Tata Power Renewables", sector: "Solar Energy", location: "Mumbai & Pune", activeHires: 540, verifiedHires: 535, avgStartingWage: 22000, sixMonthRetention: "88%", contactPerson: "Kavita Rao", status: "Active Partner" },
];

export const initialAlerts = [
  {
    id: "ALT-01",
    category: "Low Placement",
    title: "Low Placement Alert: Retail Sales in Jaipur Center",
    description: "Kaushal Pragati's Retail Sales batch in Jaipur recorded only 52% placement within 90 days, below the mandated 70% benchmark.",
    severity: "high",
    targetEntity: "Kaushal Pragati (Jaipur)",
    status: "Pending Action",
    date: "25 Sep 2026",
    actionRequired: "Issue warning directive and conduct employer alignment round",
  },
  {
    id: "ALT-02",
    category: "High Dropout",
    title: "High Dropout Alert: Data Entry Cohort in Hyderabad",
    description: "Nirmaan Trust reported a 28% attrition rate in Batch 2025-DAT-C during weeks 4-6, triggering automatic audit notification.",
    severity: "high",
    targetEntity: "Nirmaan Trust (Hyderabad)",
    status: "Under Review",
    date: "24 Sep 2026",
    actionRequired: "Initiate counselor review & examine attendance logs",
  },
  {
    id: "ALT-03",
    category: "Skill Gap",
    title: "Skill Gap Alert: EV Battery Diagnostics Shortage",
    description: "14 automotive employers in Kolkata & Pune reported that incoming EV apprentices lack hands-on battery pack diagnosis experience.",
    severity: "medium",
    targetEntity: "All EV Training Providers",
    status: "Directive Dispatched",
    date: "22 Sep 2026",
    actionRequired: "Mandate 40 hours simulator/bench lab training for battery troubleshooting",
  },
  {
    id: "ALT-04",
    category: "Poor Performing",
    title: "Poor-performing Program Alert: Basic Retail Batch",
    description: "Retail sales placement wages have stagnated at ₹14,000 against state median of ₹18,450. Sector skills council audit initiated.",
    severity: "medium",
    targetEntity: "Retail Sector Skill Council",
    status: "Pending Action",
    date: "21 Sep 2026",
    actionRequired: "Re-evaluate qualification pack and incorporate e-commerce supply chain modules",
  },
  {
    id: "ALT-05",
    category: "Required Intervention",
    title: "Mandatory Intervention: Trainee Consent Expiry Reminder",
    description: "128 trainees from Q1-2025 cohort have consent renewals due this month under DPDP Act 2023 compliance guidelines.",
    severity: "low",
    targetEntity: "All Training Centers",
    status: "In Progress",
    date: "20 Sep 2026",
    actionRequired: "Dispatch automated WhatsApp consent renewal questionnaire",
  },
];

export const initialVerificationHistory = [
  { id: "VER-8801", traineeId: "SK-24018", name: "Aarav Mehta", employer: "SunGrid Energy", role: "Solar Technician", wage: 18500, verifiedBy: "Rohan Desai", verifiedAt: "12 Aug 2026", status: "Confirmed" },
  { id: "VER-8802", traineeId: "SK-24027", name: "Priya Nair", employer: "Aster Medcity", role: "Patient Care Assistant", wage: 21000, verifiedBy: "Dr. Rachel Thomas", verifiedAt: "15 Aug 2026", status: "Confirmed" },
  { id: "VER-8803", traineeId: "SK-24041", name: "Kavya Reddy", employer: "Self-employed", role: "Freelance Data Operator", wage: 24000, verifiedBy: "District Skill Officer (Hyd)", verifiedAt: "20 Aug 2026", status: "Confirmed" },
  { id: "VER-8804", traineeId: "SK-24063", name: "Meena Kumari", employer: "CareWell Clinic", role: "Care Assistant", wage: 17500, verifiedBy: "Dr. S. K. Roy", verifiedAt: "28 Aug 2026", status: "Confirmed" },
  { id: "VER-8805", traineeId: "SK-24072", name: "Rohan Varma", employer: "SunGrid Energy", role: "Solar Installer", wage: 19000, verifiedBy: "Rohan Desai", verifiedAt: "05 Sep 2026", status: "Confirmed" },
];

export const initialAuditLogs = [
  { id: "AUD-101", action: "VERIFY_EMPLOYMENT", actor: "Rohan Desai (Employer)", entity: "Trainee SK-24072", details: "Confirmed role Solar Installer and monthly wage ₹19,000", timestamp: "Today, 11:24 AM" },
  { id: "AUD-102", action: "ISSUE_DIRECTIVE", actor: "Ananya Sharma (Govt Admin)", entity: "Alert ALT-03", details: "Dispatched curriculum upgrade directive for EV battery diagnostics", timestamp: "Yesterday, 04:15 PM" },
  { id: "AUD-103", action: "EXPORT_REPORTS", actor: "Farah Khan (Provider)", entity: "Batch 2024-SOL-A", details: "Exported placement CSV for 30 participants", timestamp: "Yesterday, 02:40 PM" },
  { id: "AUD-104", action: "UPDATE_WAGE", actor: "Rohan Desai (Employer)", entity: "Trainee SK-24018", details: "Updated wage from ₹15,500 to ₹18,500 (+18%)", timestamp: "24 Sep 2026" },
  { id: "AUD-105", action: "CONSENT_RENEWED", actor: "Aarav Mehta (Trainee)", entity: "Consent Profile", details: "Granted 12-month follow-up consent via WhatsApp check-in", timestamp: "23 Sep 2026" },
];

export const initialUsers = [
  { id: "USR-01", name: "Ananya Sharma", email: "admin.ananya@kaarya.gov.in", role: "National Super Admin", districtAccess: "All India (National)", status: "Active", lastActive: "Active now" },
  { id: "USR-02", name: "Rohan Desai", email: "rohan.desai@sungrid.example", role: "Employer People Ops", districtAccess: "Corporate / Pune", status: "Active", lastActive: "10 mins ago" },
  { id: "USR-03", name: "Farah Khan", email: "farah.khan@udaan.example", role: "Provider Administrator", districtAccess: "Pune & Kolkata", status: "Active", lastActive: "25 mins ago" },
  { id: "USR-04", name: "K. S. Narayanan", email: "dso.pune@maharashtra.gov.in", role: "District Skill Officer", districtAccess: "Pune District", status: "Active", lastActive: "1 hour ago" },
  { id: "USR-05", name: "Shalini Verma", email: "auditor.s@gov.in", role: "Compliance Inspector", districtAccess: "Western Region", status: "Active", lastActive: "Yesterday" },
];

export const initialConsentLedger = [
  { id: "CSNT-01", traineeId: "SK-24018", name: "Aarav Mehta", purpose: "Outcome tracking & 1-year wage verification", grantedOn: "12 Jan 2025", channel: "WhatsApp OTP", status: "Active", expiresOn: "12 Jan 2027" },
  { id: "CSNT-02", traineeId: "SK-24027", name: "Priya Nair", purpose: "Post-training employment check-ins", grantedOn: "04 Mar 2025", channel: "Digital Portal Form", status: "Active", expiresOn: "04 Mar 2027" },
  { id: "CSNT-03", traineeId: "SK-24041", name: "Kavya Reddy", purpose: "Micro-enterprise outcome monitoring", grantedOn: "27 Feb 2025", channel: "SMS Confirmation", status: "Active", expiresOn: "27 Feb 2027" },
  { id: "CSNT-04", traineeId: "SK-24056", name: "Sanjay Das", purpose: "NAPS apprenticeship outcome tracking", grantedOn: "10 Apr 2025", channel: "Institute Paper Form", status: "Active", expiresOn: "10 Apr 2027" },
  { id: "CSNT-05", traineeId: "SK-24033", name: "Imran Khan", purpose: "Placement support outreach", grantedOn: "19 Jan 2025", channel: "WhatsApp OTP", status: "Active", expiresOn: "19 Jan 2027" },
];

export const initialNotifications = {
  Employer: [
    { id: 1, title: "New Trainee Hired", body: "Ananya Deshmukh (Data Entry) added to your company onboarding list.", time: "2 hours ago", unread: true },
    { id: 2, title: "Pending Verification", body: "Sanjay Das (EV Service Apprentice) awaiting your employment confirmation.", time: "5 hours ago", unread: true },
    { id: 3, title: "Quarterly Retention Report Ready", body: "Your Q2 hiring retention scorecard shows 82% 6-month retention.", time: "Yesterday", unread: false },
  ],
  "Training Provider": [
    { id: 10, title: "Batch 2025-EVS-A Completed", body: "25 trainees completed practical examinations with 91% pass rate.", time: "1 hour ago", unread: true },
    { id: 11, title: "Employer Verification Confirmed", body: "SunGrid Energy verified 2 solar technicians from your Pune center.", time: "4 hours ago", unread: true },
    { id: 12, title: "New NSQF Level 4 Standards Issued", body: "Ministry of Skill Development released updated criteria for Solar PV.", time: "2 days ago", unread: false },
  ],
  "Government / Admin": [
    { id: 20, title: "Critical Placement Alert", body: "Kaushal Pragati Jaipur fell below 55% placement benchmark.", time: "30 mins ago", unread: true },
    { id: 21, title: "State Skill Gap Report Published", body: "Western industrial belt shows 12,400 unfilled EV & solar technician roles.", time: "3 hours ago", unread: true },
    { id: 22, title: "DPDP Act Compliance Audit", body: "Consent ledger verification passed for 98.4% of active participant records.", time: "Yesterday", unread: false },
  ],
  Trainee: [
    { id: 30, title: "Quarterly Check-in Scheduled", body: "Your 6-month job satisfaction check-in is due today on WhatsApp.", time: "Just now", unread: true },
    { id: 31, title: "Certificate Ready for Download", body: "Your official NSQF Level 4 Certificate (QR-verified) is available.", time: "3 days ago", unread: false },
  ],
};

export const initialSkillGaps = [
  { skill: "EV Battery Pack Diagnostics & BMS", industryDemand: 88, courseCoverage: 46, gap: 42, priority: "High", sector: "Automotive", recommendedAction: "Introduce 40 hours hardware fault simulator module" },
  { skill: "Grid-Tied Inverter Commissioning", industryDemand: 82, courseCoverage: 62, gap: 20, priority: "Medium", sector: "Solar Energy", recommendedAction: "Provide hands-on testing bench in tier-2 centers" },
  { skill: "ICU Patient Monitoring & Infusion Pumps", industryDemand: 91, courseCoverage: 68, gap: 23, priority: "High", sector: "Healthcare", recommendedAction: "Partner with district civil hospitals for 2-week clinical rounds" },
  { skill: "Automated POS & Inventory Audit", industryDemand: 74, courseCoverage: 51, gap: 23, priority: "Medium", sector: "Retail", recommendedAction: "Upgrade software labs from legacy billing to modern ERP POS" },
  { skill: "Data Cleaning & Advanced Lookup Models", industryDemand: 85, courseCoverage: 76, gap: 9, priority: "Low", sector: "IT-ITeS", recommendedAction: "Cover Power Query and basic Python script automation" },
];

export const geographicalData = [
  { district: "Pune", state: "Maharashtra", centers: 8, enrolled: 3420, certified: 3180, placed: 2668, placementRate: 78, retentionRate: 84, avgWage: 19200, primaryGap: "PLC & Industrial Automation" },
  { district: "Kochi", state: "Kerala", centers: 6, enrolled: 2240, certified: 2060, placed: 1635, placementRate: 73, retentionRate: 79, avgWage: 20800, primaryGap: "Elderly Care Specialized Protocols" },
  { district: "Jaipur", state: "Rajasthan", centers: 5, enrolled: 1980, certified: 1740, placed: 1168, placementRate: 59, retentionRate: 64, avgWage: 15600, primaryGap: "EV High Voltage Battery Handling" },
  { district: "Hyderabad", state: "Telangana", centers: 7, enrolled: 2890, certified: 2650, placed: 1936, placementRate: 67, retentionRate: 74, avgWage: 18900, primaryGap: "Cloud Collaboration & PowerBI" },
  { district: "Kolkata", state: "West Bengal", centers: 5, enrolled: 1820, certified: 1620, placed: 1128, placementRate: 62, retentionRate: 71, avgWage: 16400, primaryGap: "Motor Diagnostics & Regenerative Systems" },
  { district: "Patna", state: "Bihar", centers: 4, enrolled: 1450, certified: 1290, placed: 877, placementRate: 60, retentionRate: 68, avgWage: 15200, primaryGap: "Modern Patient Hygiene & Equipment" },
  { district: "Lucknow", state: "Uttar Pradesh", centers: 6, enrolled: 2150, certified: 1910, placed: 1380, placementRate: 64, retentionRate: 72, avgWage: 16100, primaryGap: "Hospital Aseptic Preparation" },
  { district: "Bengaluru", state: "Karnataka", centers: 9, enrolled: 4120, certified: 3890, placed: 3345, placementRate: 81, retentionRate: 87, avgWage: 22400, primaryGap: "AI Data Annotation & Micro-services" },
];
